apiVersion: v1
kind: Service
metadata:
  name: infinite-canvas-service
spec:
  type: NodePort
  selector:
    app: infinite-canvas
  ports:
    - name: nextjs-port
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000
    - name: metrics-port
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001

